repos:
  - repo: local
    hooks:
      - id: pants_tailor
        name: Pants tailor (bash)
        entry: bash -c 'pants tailor ::'
        language: system
      - id: pants_format
        name: Pants format (bash)
        entry: bash -c 'pants fmt ::'
        language: system
      - id: pants_lint
        name: Pants lint (bash)
        entry: bash -c 'pants lint ::'
        language: system
      - id: pants_fix
        name: Pants fix (bash)
        entry: bash -c 'pants fix ::'
        language: system
