version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_async.txt
    - requirements: requirements_doc.txt

sphinx:
  configuration: docs/source/conf.py

