[GLOBAL]
pants_version = "2.15.1"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.bandit",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.pyupgrade",
    "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["CPython>=3.9.*"]

[anonymous-telemetry]
enabled = false

[source]
marker_filenames = [
    "pyproject.toml"
]

[black]
config_discovery = "True"

[bandit]
config = "bandit.yaml"

[autoflake]
args = ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place", "--recursive", "--ignore-init-module-imports"]

[isort]
config_discovery = "True"
